src/Entity/Building.php
<?php

namespace App\Entity;

use App\Repository\BuildingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BuildingRepository::class)
 */
class Building
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(min="4",max="48")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $windows;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $overtime;

    /**
     * @ORM\Column(type="date")
     */
    private $date_washed;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getWindows(): ?string
    {
        return $this->windows;
    }

    public function setWindows(string $windows): self
    {
        $this->windows = $windows;

        return $this;
    }

    public function getOvertime(): ?string
    {
        return $this->overtime;
    }

    public function setOvertime(string $overtime): self
    {
        $this->overtime = $overtime;

        return $this;
    }

    public function getDateWashed(): ?\DateTimeInterface
    {
        return $this->date_washed;
    }

    public function setDateWashed(\DateTimeInterface $date_washed): self
    {
        $this->date_washed = $date_washed;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Form/BuildingType.php
<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class BuildingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('address',TextType::class)
            ->add('city',TextType::class)
            ->add('number',IntegerType::class, [
                'help' => 'Street number'
            ])
            ->add('windows',ChoiceType::class,[
                'choices' => [
                    'Yes' => 'Yes',
                    'No' => 'No'
                ],
                'help' => 'Windows washed - Yes or No'
            ])
            ->add('overtime',TextType::class)
            ->add('date_washed',DateType::class,[
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'js-datepicker'
                ],
                'html5' => false
            ]);
    }



}

src/Controller/BuildingController.php
<?php

namespace App\Controller;

use App\Entity\Building;
use App\Form\BuildingType;
use App\Repository\BuildingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class BuildingController extends AbstractController
{


    /**
     * @Route("/buildings", name="buildings")
     * @param BuildingRepository $buildingRepository
     * @return Response
     */
    public function home(BuildingRepository $buildingRepository,Request $request,PaginatorInterface $paginator)
    {

        $buildings = $buildingRepository->findAll();

        $pagination = $paginator->paginate(
            $buildings, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('building/home.html.twig',[
            'pagination' => $pagination,

        ]);
    }

    /**
     * @Route("building/add", name="add")
     * @param EntityManagerInterface $em
     * @param Request $request
     *
     * @param ValidatorInterface $validator
     * @return RedirectResponse|Response
     */

    public function add(EntityManagerInterface $em,Request $request,ValidatorInterface $validator){

        $form = $this->createForm(BuildingType::class);
        $form->handleRequest($request);



        if ($form->isSubmitted() && $form->isValid()){
            //dd($form->getData());
            $data = $form->getData();
            $building = new Building();

            $building->setAddress($data['address']);
            $building->setCity($data['city']);
            $building->setNumber($data['number']);
            $building->setWindows($data['windows']);
            $building->setOvertime($data['overtime']);
            $building->setDateWashed($data['date_washed']);

            // test for errors
            // if any error -> goes to template validation
            $errors = $validator->validate($building);
            if (count($errors) > 0){
                return $this->render('building/validation.html.twig', [
                    'errors' => $errors,
                ]);
            }
            $em->persist($building);
            $em->flush();

            $this->addFlash('success','You added a new building');

            return $this->redirectToRoute('buildings');
        }

        return $this->render('building/add.html.twig',[
            'buildingForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("building/edit/{id}", name="edit")
     * @param Building $building
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return RedirectResponse|Response
     */
    public function edit(Building $building, Request $request, EntityManagerInterface $em){


        $form = $this->createForm(BuildingType::class,$building);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $em->persist($building);
            $em->flush();


            $this->addFlash('success','You edited successfully');

            return $this->redirectToRoute('buildings',[
                'id' => $building->getId()
            ]);
        }

        return $this->render('building/edit.html.twig',[
            'buildingForm' => $form->createView(),

        ]);
    }

    /**
     * @Route("building/delete/{id}", name="delete")
     * @param Building $building
     * @param EntityManagerInterface $em
     * @return RedirectResponse
     */

    public function delete(Building $building,EntityManagerInterface $em){
        $deleteBuilding = $em->getRepository(Building::class)->find($building);
        $em->remove($deleteBuilding);
        $em->flush();
        return $this->redirectToRoute('buildings');
    }
}

templates/building/add.html.twig
{% extends('base.html.twig') %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    <script>
        $(document).ready(function() {

            $('.js-datepicker').datepicker({
                format:'yyyy-mm-dd'
            });

        });
    </script>
{% endblock %}
{% block body %}
    <div class="container">
    <h1>Hello</h1>
    {{ form_start(buildingForm) }}

        {{ form_widget(buildingForm) }}

    <button type="submit" class="btn btn-primary mb-5 pl-5 pr-5">Add</button>
    {{ form_end(buildingForm) }}
    </div>
{% endblock %}

templates/building/edit.html.twig
{% extends('base.html.twig') %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    <script>
        $(document).ready(function() {

            $('.js-datepicker').datepicker({
                format:'yyyy-mm-dd'
            });

        });
    </script>
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Edit building</h1>
        {{ form_start(buildingForm) }}

        {{ form_widget(buildingForm) }}

        <button type="submit" class="btn btn-warning mb-5 pl-5 pr-5">Edit</button>
        {{ form_end(buildingForm) }}
    </div>
{% endblock %}

templates/building/home.html.twig
{% extends('base.html.twig') %}

{% block title %}List of buildings{% endblock %}


{% block body %}
    <div class="container">

        <h2 class="">Building info ({{ pagination.getTotalItemCount }} buildings)
            <span class="ml-5">
                <a href="{{ path('add') }}"><button type="button" class="btn btn-primary" >Add</button></a>
            </span>
            {#<span class="ml-1">
                <a href=""><button type="button" class="btn btn-warning checkbox-show" id="edit" >Edit</button></a>
            </span>
            <span class="ml-1">
                <a href=""><button type="button" class="btn btn-danger" >Delete</button></a>
            </span>#}
        </h2>

        <table class="table table-responsive table-striped">
            <thead>
                <tr>
                    <th>Address</th>
                    <th>Number</th>
                    <th>City</th>
                    <th>Windows</th>
                    <th>Overtime</th>
                    <th>Washed On *</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for building in pagination %}
                <tr>

                    <td>{{ building.address }}</td>
                    <td>{{ building.number }}</td>
                    <td>{{ building.city }}</td>
                    <td>{{ building.windows }}</td>
                    <td>{{ building.overtime }}</td>
                    <td>{{ building.dateWashed|date('m-d-Y') }}</td>
                    <td><span class="ml-1">
                <a href="{{ path('edit', {
                        id:building.id
                    })
                }}"><button type="button" class="btn btn-warning" >Edit</button></a>
            </span>
                    <span class="mt-1">
                <a href="{{ path('delete', {
            id:building.id}) }}"><button type="button" class="btn btn-danger" >Delete</button></a>
            </span>
                    </td>
                </tr>

                {% endfor %}

            </tbody>


        </table>
        <br>
        <p class="small">* mm/dd/yyyy</p>
        <div class="w-75 d-flex justify-content-center">
            {{ knp_pagination_render(pagination) }}
        </div>


    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}




{% endblock %}

templates/building/validation.html.twig
{#
        Example of handling error messages and validation
#}
<h3>There are errors:</h3>
<ul>
    {% for error in errors %}
        <li>{{ error.message }}</li>
    {% endfor %}
</ul>